@host = localhost:3000
@email = test@test.com
@password = test

### Register user account
POST http://{{host}}/api/auth/register
Content-Type: application/json

{
   "email": "{{email}}",
   "password": "{{password}}"
}


### Login into user account
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
   "email": "{{email}}",
   "password": "{{password}}"
}